# Generated by Django 4.1.3 on 2022-12-13 14:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proyectofinal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Androide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('utilidad', models.CharField(choices=[('Astromecánico', 'Astromecánico'), ('Asesino', 'Asesino'), ('Protocolo', 'Protocolo'), ('Otro', 'Otro')], default=1, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numero_sith', models.IntegerField()),
                ('titulo_sith', models.CharField(choices=[('Aprendíz', 'Aprendíz'), ('Lord', 'Lord'), ('Maestro', 'Maestro')], default=1, max_length=100)),
                ('estado', models.CharField(choices=[('Vivo', 'Vivo'), ('Muerto', 'Muerto'), ('Desconocido', 'Desconocido')], default=3, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='jedi',
            name='creado',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jedi',
            name='color_sable',
            field=models.CharField(choices=[('Azul', 'Azul'), ('Verde', 'Verde'), ('Amarillo', 'Amarillo'), ('Violeta', 'Violeta'), ('Blanco', 'Blanco')], default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='jedi',
            name='titulo',
            field=models.CharField(choices=[('Iniciado', 'Iniciado'), ('Padawan', 'Padawan'), ('Caballero', 'Caballero'), ('Maestro', 'Maestro'), ('Maestro de la Orden', 'Maestro de la Orden')], default=1, max_length=100),
        ),
    ]
