# Generated by Django 4.1.3 on 2022-12-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedi_bootstrap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publicado_el',
            field=models.DateField(auto_now_add=True),
        ),
    ]
