# Generated by Django 4.1.3 on 2022-12-28 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jedi_bootstrap', '0002_alter_post_publicado_el'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null='True', upload_to='imagenes')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='imagen_post', to='jedi_bootstrap.post')),
            ],
        ),
    ]
