# Generated by Django 4.1.3 on 2022-12-28 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedi_bootstrap', '0004_post_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FotoPost',
        ),
    ]
