# Generated by Django 4.1.3 on 2022-12-28 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedi_bootstrap', '0006_mensajes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mensajes',
            new_name='Mensaje',
        ),
    ]
